source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NWSTokenView_Example' do
  pod "NWSTokenView", :path => "../"
end

target 'NWSTokenView_Tests' do
  pod "NWSTokenView", :path => "../"
end
